export enum MasterData {
  IdType = "getIdCardTypeByApplicantType",
  ApplicationTypeCode = "getApplicationTypeListByCompany",
  Branches = "getBranchList",
  DealerByBranch = "getDealerByBranch",
  FPGroupByDealerAndBranch = "getFPGroupByDealerAndBranch",
  FPCampaignByGroupAndDealerAndBranch = "getFPCampaignByGroupAndDealerAndBranch",
  AddressTypeList = "getAddressTypeList",
  ResidenceType = "getResidenceType",
  HousingOwnership = "getHousingOwnership",
  PhoneTypeListByCompanyId = "getPhoneTypeListByCompanyId",
  AddressStatus = "getAddressStatus",
  AllProvincesByCountryId = "getAllProvincesByCountryId",
  kotamadyasByProvinceId = "getkotamadyasByProvinceId",
  kecamatansListBykotamadyasId = "getkecamatansListBykotamadyasId",
  kelurahanListBykecamatansId = "getkelurahanListBykecamatansId",
  LocationDetails = "getLocationDetails",
  RelationshipTypeListByCompanyId = "getRelationshipTypeListByCompanyId",
  DocumentListByCompanyId = "getDocumentListByCompanyId",
  CancellationReason = "getCancellationReason",
  MaritalStatus = "getMaritalStatus",
  AssetCondition = "getAssetCondition",
  AssetUsage = "getAssetUsage",
  AssetMake = "getAssetMake",
  Occupations = "getOccupations",
  CreditApprovalType = "getCreditApprovalType",

  AllCompanies = "getSubsidaryCompanies",
  CurrencyType = "getCurrencyType",
  ApplicantCodeType = "getApplicantCodeType",
  ApplicantCategoryCode = "getApplicantCategoryCode",
  MarketingOfficerByBranch = "getMarketingOfficerByBranch",
  FinancialProductGroupbyCompany = "getFinancialProductGroupbyCompany",

  ApplicationSource="GetApplicationSourceLookup",
  TitleCode = "getTitleCode",
  DebtorCategoryCode = "getDebtorCategoryCode",
  Nationality = "getNationality",
  GenderCode = "getGenderCode",
  EducationDegreeStatus = "getEducationDegreeStatus",
  Religion = "getReligion",
  CreditRating = "getCreditRating",
  Citizenship = "getCitizenship",
  CountryDomicile = "getCountryDomicile",
  TitleSuffix = "getTitleSuffix",
  CrditPurpose = "getCrditPurpose",
  TransmissionType = "getTransmissionType",
  AssetModelColour = "getAssetModelColour",
  VehicleStyle = "getVehicleStyle",
  AllKotamadya = "getAllKotamadya",
  OperatorVehicle = "getOperatorVehicle",
  UsageArea = "getUsageArea",
  GoodsServicesFunds = "getGoodsServicesFunds",
  Banks = "GetAllBanks",
  BankBranches = "GetBankBranches",
  AccounTypes = "GetAccounTypes",

  EmploymentType = "getEmploymentType",
  EmploymentStatus = "getEmploymentStatus",
  Designation = "getDesignation",
  RentalTypes="GetRentalTypes",
  Department = "getDepartment",
  EconomicSector = "getEconomicSector",
  BusinessType = "getBusinessType",
  BusinessLine = "getBusinessLine",
  ReferenceType = "GetReferenceType",
  ReferenceBusinessType = "getReferenceBusinessType",
  RepresentativeType = "getRepresentativeType",
  Signatory = "getSignatory",
  ExtractFamilyExposureType = "GetExtractFamilyExposureType",
  SpAgreementType = "getSpAgreementType",
  Relationships = "getRelationships",

  FinancingType = "getFinancingType",
  Bpkbreceivedstatus = "getbpkbreceivedstatus",
  Bpkbstatus = "getbpkbstatus",
  Owner = "getOwner",
  Bpkbownercategory = "getbpkbownercategory",

  OLReceiptingBank = "getOLReceiptingBank",
  InvoiceOptionOL = "getInvoiceOptionOL",
  AccountingTypeOL = "getAccountingTypeOL",
  RentalModes = "getRentalMode",
  Frequencies = "getPaymentFrequency",
  AssetModelAndFitting = "getAssetModelAndFitting",

  AssetType = "getAssetType",
  AssetSubType = "getAssetSubType",
  CAPAssetMake = "getCAPAssetMake",
  AssetBrand = "getBrand",
  AssetModel = "getAssetModel",
  AssetSelection = "getAssetSelection",
  PoliceCategory = "getPoliceCategory",

  BBNAgent = "getBBNAgent",
  RVBaloonApplicable = "GetRVBaloonApplicable",

  FieldInvestigator = "getMarketingOfficerByBranch",
  SocialInteraction = "getSocialInteractionCodeLookUp",
  OfficeLocation = "getPropertyLocationLookUp",
  FiRating = "getCreditRatingLookup",
  MeetWith = "getMeetTypeCodeLookUp",
  AssetComponents = "getAssetComponents",
  AmountComponents = "getAmountComponents",

  // IOPs master data enums
  IOPsAssetBrand = "IOPsgetBrand",
  IOPsAssetModel = "IOPsgetAssetModel",

  // truck detail masterdata
  PropertyLocation = "getPropertyLocationLookUp",
  OperatingObjective="getOperatingObjectiveLookUp",
  BodyType="getBodyTypeLookUp",
  PurchasingObjective="getPurchasingObjectiveLookUp",
  IndustryTypeCode="getIndustryTypeCodeLookup",
  TruckCategoryCode="getTruckCategoryCodeLookUp",

  POSLocationCode="GetPOSLocationCodeLookup",
  GetSalesmanByDealer="GetSalesmanByDealer"

}