export enum QueueOperation {
    VIEW = "View",
    CANCEL = "Cancel Request",
    EDIT = "Edit",
    SUBMIT = "Submit",
    ASSIGN_To_VO = "ASSIGN_To_VO",
    RE_ASSIGN_To_VO = "RE_ASSIGN_To_VO",
    COPY = "Copy",
    VISIT = "Field Visit Feedback",
    DOCUMENT = "Document Tracking",
    POINTSCORE = "Point_Score",
    REJECT = "Reject",
    OVPSTATIONERY = "OVP Stationery",
    RESCOURING = "Rescoring",
    CHANGEREQUEST="Change Request",
    RESUBMIT="Re-Submit For Approval",
    WITHDRAWREQUEST = "Withdraw Request",
    EAPPROVAL="E-Approval",
    SUBMITFORAPPROVAL="Submit For Approval",
    CancelRejectComments= "Application Cancel / Reject Comments",
    ReSurvey="mPOS Resurvey",
    PRINT="Print",
    Forward= "Forward",
    TakeControl= "Take Control",
    ForwardtoBM= "Forward to BM",
    CaRecommendation = "CA Recommendation"
}