import { IBaseEntity } from "@NFS_Entity/Base-Entity/BaseEntity.model";
import { Control } from "src/Library";

export interface IPRPLInfo extends IBaseEntity {
  PROPOSALID: number;
  PROPOSALNBR: string;
  EXECUTIONDTE: Control<Date>;
  PROPOSALTYPECDE: string;
  //CODE: string;
  APPLICANTIND: string;
  PROPOSALDTE: Control<Date>;
  COMMENTS: string;
  STATUSCDE: string;
  QUOTENAME: string;
  CONTACT: string;
  INTRODUCERREFERENCE: string;
  BPCOMPANYID: number;
  BPCOMPANYBRANCHID: number;
  BPINTRODUCERID: number;
  BPINTRODUCERBRANCHID: number;
  FPGROUPID: number;
  FINANCIALPRODUCTID: number;
  FINANCETYP: string;
  EXECUTIONOFFSET: number;
  SESSIONID: number;
  SESSIONCDE: string;
  WORKFLOWINSTANCEID: string;
  ISCOMPLETED: string;
  ISSUCCESS: string;
  ISCANCELLED: string;
  CNFGTPLEID: number;
  INTRODUCERROLECDE: string;
  CREATEDBY: number;
  CURRENCYCDE: string;
  SALESCHANNELCDE: string;
  CANCELLATIONCOMMENT: string;
  CONTREFNO: string;
  ACTIVEIND: boolean;
  OTOAPLTCTGYCDE: string;
  MARKETINGOFFICERID: number;
  POINTOFSALELOCATIONCDE: string;
  PACKAGECDE: string | null;
  PACKAGEEXPIRYDTE: Control<Date>;
  ISUREAPPLICATIONNBR: string;
  POEXPIRYDTE: Control<Date>;
  CONTRACTNBR: string;
  OVPPRINTIND: boolean;
  COPIEDFROMAPPNBR: string;
  ISREVISED: boolean;
  ISPACKAGE: boolean;
  ISFROMMPOS: boolean;
  MPOSAPPLICATIONNBR: string;
  MARKETINGHEADID: number;
  MARKETINGCOORDINATORID: number;
  CMOTLDESG: string;
  READIND: boolean;
  MCOMDEALER: boolean;
  ISMCOMCAMPAIGN: boolean;
  STATUSCHANGEBY: number;
  ORIGINALCONTRACTNBR: string;
  QSTOKEN: string;
  REASONCODE: string;
  ISREJECTED: boolean;
  MCOMTOPUPIND: boolean;
  OVRDRJTDBY: string;
  OVRDIND: boolean;
  // following properties are from helper class
  PROPOSALDTE_Helper:Control<Date>;
  FINANCIALPRODUCTNME: string;
  PROPOSALTYPECDEOLD: string;
  EAPPROVALIND: boolean;
  EAPPROVALTIME: Control<Date>;
  REQUESTSTATUSDSC: string;
  BUSINESSPARTNERNME: string;
  ASSETMAKEDSC: string;
  ASSETMODELDSC: string;
  FINANCEDAMT: number;
  BPINTRODUCERNME: string;
  BPINTRODUCERBRANCHNAME: string;
  BPCOMPANYBRANCHNME: string;
  FPGROUP: string;
  FINANCECOMPANY: string;
  BRANCH: string;
  BUSINESSPARTNER: string;
  BUSINESSPARTNERBRANCH: string;
  CUSTOMERNME: string;
  CurrencySymbol: string;
  CONTRACTID: number;
  FPGROUPINITNAME: string;
  ENGINENUMBER: string;
  CHASSISNBROTO: string;
  CUSTOMERNBR: string;
  CONTRACTSTS: string;
  POSLOCATION: string;
  CONFLICTDETECTED: boolean;
  POINTSCOREEVALUATED: boolean;
  SCORECARDEVALUATIONIND: boolean;
  OLRCPTNGBNK: number | null;
  ISAPPLICATIONREJECTED: boolean;
  ASSNTO: number;
  ROWVERSION: string;
  CRDTRCMDIND?: boolean ;
  CRDTRCMDTYPCDE: string;
  CRDTRCMDINDDESC:string;
  OTOTACaplcind: boolean;
  COMMAPPLICABLECDE: string;
  ENABLEGOODSDETAILS: boolean;
  ISGOODSDETAILSMANDATORY :boolean;
  SALESMANID: number;
  SALESMANMANDATORY: boolean;
  SALESMANENABLE :boolean;
}
