export {IPRPLInfo} from './IPRPLInfo.model';
export { IProposalApplicantEntity} from './ProposalApplicantEntity/IProposalApplicantEntity.model';
export { IProposalArticleEntity} from './ProposalArticleEntity/IProposalArticleEntity.model';
export { IPRPL_BSNS_RULEInfo} from './IPRPL_BSNS_RULEInfo.model';
export { IPRPL_EGLE_SCRE_TWOInfo} from './IPRPL_EGLE_SCRE_TWOInfo.model';
export { IPRPL_RESN_CODEInfo} from './IPRPL_RESN_CODEInfo.model';
export { IPRPL_TPLE_RNTL_INTInfo} from './IPRPL_TPLE_RNTL_INTInfo.model';
export { IPRPL_CHRTInfo} from './IPRPL_CHRTInfo.model';
export { IProposalRoundingTemplateEntity} from './IProposalRoundingTemplateEntity.model';
export { IPRPL_TPLE_RONDInfo} from './IPRPL_TPLE_RONDInfo.model';
export { IPRPL_TPLE_ROND_DETLInfo} from './IPRPL_TPLE_ROND_DETLInfo.model';
export { IPRPL_CMPT_CNFGInfo} from './IPRPL_CMPT_CNFGInfo.model';
export { IPRPL_CONT_MPNGInfo} from './IPRPL_CONT_MPNGInfo.model';
export { IProposalTaxConfigEntity} from './IProposalTaxConfigEntity.model';
export { IPRPL_TAX_CMPTInfo} from './IPRPL_TAX_CMPTInfo.model';
export { IProposalTaxConfigDetailEntity} from './IProposalTaxConfigDetailEntity.model';
export { IPRPL_TAX_CDTN_RLSPInfo} from './IPRPL_TAX_CDTN_RLSPInfo.model';
export { IPRPL_TAX_CMPT_CDTNInfo} from './IPRPL_TAX_CMPT_CDTNInfo.model';
export { IPRPL_TAX_PRTY_DETLInfo} from './IPRPL_TAX_PRTY_DETLInfo.model';
export { IPRPL_TPLE_COMM_CNFGInfo} from './IPRPL_TPLE_COMM_CNFGInfo.model';
export { IPRPL_TPLE_INCM_CNFGInfo} from './IPRPL_TPLE_INCM_CNFGInfo.model';
export { IPRPL_ISRE_MPNGInfo} from './IPRPL_ISRE_MPNGInfo.model';
export { IPRPL_IOPS_USERInfo} from './IPRPL_IOPS_USERInfo.model';
export { IPRPL_DVTN_TRCK } from '../../ProposalDTS-Entity/IPRPL_DVTN_TRCK.model';