import { IBaseEntity } from "@NFS_Entity/Base-Entity/BaseEntity.model";
import { Control } from "src/Library";
import {
    IPRPL_ASETInfo, IPRPL_FINL_AGRMInfo, IProposalArticleComponentEntity, IPRPL_AIR_CRFT_DETLInfo, IPRPL_ENGN_DETLInfo,
    IPRPL_EQPT_DETLInfo, IPRPL_VHCL_DETLInfo, IOTO_PRPL_ASST_BPKB_DETLInfo, IPRPL_SHIP_DETLInfo, IPRPL_RLST_DETLInfo,
    IPRPL_ACCYInfo, IProposalChargeEntity, IPRPL_RNTL_DETLInfo, IProposalRepaymentPlanEntity, IPRPL_ASET_INSRInfo, IMainInsuranceEntity,
    IOTO_PRPL_ASET_ADDL_INSRInfo, IPRPL_ARTE_CHRT_DETLInfo, IPRPL_ARTE_BASE_RATEInfo, IPRPL_ADMN_FEE_DETLInfo, IPRPL_SBSD_DETLInfo,
    IPRPL_JP2_COMM_DETLInfo, IPRPL_RNTL_CMPT_CNFGInfo, IPRPL_BPKB_RPRS_DETLInfo, IPRPL_BPKB_GRTR_DETLInfo, ISTND_INSR_DETL_CHRTInfo, ISTND_INSR_CHRTInfo, IProposalTruckDetailEntity,
    IOTO_BPKB_SRCHInfo, IPRPL_PRVN_FEE_DETLInfo, IProposalCommissionEntity, IPRPL_SOF_COMM_DETLInfo, IFINE_TYPE_INCM_CNFGInfo
} from './ProposalArticleEntity.model.index';

export interface IAssetEntity extends IBaseEntity {
    PROPOSALASSET: IPRPL_ASETInfo;
    PROPOSALFINANCIALAGREEMENT: IPRPL_FINL_AGRMInfo;
    PRPLARTICLECOMPONENTENTITYCOL: Array<IProposalArticleComponentEntity>;
    //PROPOSALAIRCRAFTDETAIL: IPRPL_AIR_CRFT_DETLInfo;
    PROPOSALENGINEDETAIL: Array<IPRPL_ENGN_DETLInfo>;
    //PROPOSALEQUIPMENTDETAIL: IPRPL_EQPT_DETLInfo;
    PROPOSALVEHICLEDETAIL: IPRPL_VHCL_DETLInfo;
    OTOPRPLASSTBPKBDETL: IOTO_PRPL_ASST_BPKB_DETLInfo;
    PROPOSALSHIPDETAIL: IPRPL_SHIP_DETLInfo;
    PROPOSALREALESTATEDETAIL: IPRPL_RLST_DETLInfo;
    PROPOSALACCESSORY: Array<IPRPL_ACCYInfo>;
    PROPOSALCHARGE: Array<IProposalChargeEntity>;
    PROPOSALRENTALDETAIL: Array<IPRPL_RNTL_DETLInfo>;
    PROPOSALREPAYMENTPLANENTITYCOL: Array<IProposalRepaymentPlanEntity>;
    PROPOSALASSETINSURANCE: Array<IPRPL_ASET_INSRInfo>;
    PROPOSALINSURANCEMAIN: Array<IMainInsuranceEntity>;
    OTOPRPLASETADDINSR: Array<IOTO_PRPL_ASET_ADDL_INSRInfo>;
    PROPOSALARTICLECHARTDETL: Array<IPRPL_ARTE_CHRT_DETLInfo>;
    PROPOSALARTICLEBASERATE: Array<IPRPL_ARTE_BASE_RATEInfo>;
    PROPOSALADMINFEEDETAIL: IPRPL_ADMN_FEE_DETLInfo;
    PROPOSALSUBSIDYDETAIL: IPRPL_SBSD_DETLInfo;
    PROPOSALJP2COMMISSIONDETAIL: Array<IPRPL_JP2_COMM_DETLInfo>;
    PRPLRNTLCMPTCNFG: Array<IPRPL_RNTL_CMPT_CNFGInfo>;
    OTOPRPLASSTBPKBRPRSDETL: Array<IPRPL_BPKB_RPRS_DETLInfo>;
    OTOPRPLASSTBPKBGRTRDETL: Array<IPRPL_BPKB_GRTR_DETLInfo>;
    STNDINSRDETLCHRTInfo: ISTND_INSR_DETL_CHRTInfo;
    STNDINSRCHRTInfo: ISTND_INSR_CHRTInfo;
    TRUCKDETAILS: IProposalTruckDetailEntity;
    OTOBPKBSRCH: Array<IOTO_BPKB_SRCHInfo>;
    PROPOSALPROVISIONFEEDETAIL: IPRPL_PRVN_FEE_DETLInfo;
    PROPOSALCOMMISSIONENTITY: Array<IProposalCommissionEntity>;
    PROPOSALSOFCOMMISSIONDETAIL: IPRPL_SOF_COMM_DETLInfo;
    // following properties are from helper class
    TOTALACCESSORIESAMOUNT: number;
    TOTALCHARGESAMOUNT: number;
    FINEYPECNFG: Array<IFINE_TYPE_INCM_CNFGInfo>;
}