import { IBaseEntity } from "@NFS_Entity/Base-Entity/BaseEntity.model";
import { Control } from "src/Library";

export interface IPRPL_ASETInfo extends IBaseEntity {
    PROPOSALID: number;
    ASSETID: number;
    EXECUTIONDTE: Control<Date>;
    ASSETTYPECDE: string;
   // CODE: string;
    ASSETSUBTYPCDE: string;
    COMMENTS: string;
    QUANTITY: number;
    UNITAMT: number;
    ASSETAMT: number;
    ASSETNME: string;
    ASSETDSC: string;
    //DESCRIPTION: string;
    MAKEDSC: string;
    MODELDSC: string;
    DELIVERYDTE: Control<Date>;
    ASSETCDE: string;
    MAKECDE: string;
    BRANDCDE: string;
    MODELCDE: string;
    UNDERCONSTRUCTIONIND: string;
    TAXAMT: number;
    ASSETNAME: string;
    CONDITION: string;
    PURPOSE: string;
    BPINTRODUCERID: number;
    BRANDDSC: string;
    EXECUTIONOFFSET: number;
    SESSIONID: number;
    SESSIONCDE: string;
    ASSETMODELID: number;
    ESTMINVCDTE: Control<Date>;
    MANUFACTURERID: number;
    ROLECDE: string | null;
    ISCONVERTED: boolean;
    CONTRACTID: number;
    AGE: number;
    PLICCTGYCODEOTO: string;
    USAGETYPECODE: string;
    COUNTRYORIGIN: string;
    COUNTRYDSC:string;
    BBNAGENTID: number;
    BBNCHARGES: number;
    BPKBCHANGEOWNERSHIPIND: boolean;
    ASSETSELECTIONCDE: string;
    ARTICLEID: number;
    MCOMSEARCHTYPE: string;
    MCOMREFERENCENBR: string;
    MCOMETQUOTEID: number;
    MCOMASSETID: number;
    SUPPLIERNAME: string;
    SALESANDLEASEBACKIND: boolean;
    REVISIONID: number;
    NETBOOKVALUE: number;
    RELEASECNT: number;
    PREVASSETID: number;
    MIGRATIONIND: boolean;
    ISUSEFORBTPNREJECTED: boolean;
    //following properties are from helper class
    CONTRACTNUMBER: string;
    TYPE: string;
    ASSETTYPEDSC: string;
    ASSETSUBTYPDSC: string;
    CMCLASETUSGEDOWNPYMTPCNT: number;
    NONCMCLASETUSGEDOWNPYMTPCNT: number;
    OTOBPKBNUMBER: string;
    CONDITIONDSC: string;
    REGISTERID: number;
    TOTALROWS:number;
}