import { IBaseEntity } from "@NFS_Entity/Base-Entity/BaseEntity.model";
import { Control } from "src/Library";

export interface ICONT_EXPRInfo extends IBaseEntity {
    PROPOSALID: number;
    APPLICANTID: number;
    EXPAPPLICANTID: number;
    SEQID: number;
    REQUESTID: number;
    CONTRACTID: number;
    FACILITYTYPIND: string;
    APPLICANTTYPIND: string;
    SEARCHVALUE: string;
    ASSETMAKECDE: string;
    ASSETBRANDCDE: string;
    ASSETMODELCDE: string;
    FINANCIALPRODUCTID: number;
    NOOFTERMS: number;
    FINANCEDAMT: number;
    BPDEALERID: number;
    APPLICANTROLEIND: string;
    EXPAPPLICANTROLEIND: string;
    EXPPROPOSALID: number;
    EXPAPPLICANTTYPIND: string;
    EXPAPPLICANTNME: string;
    EXPAPPLICANTCARDID: string;
    STATUSCDE: string;
    STATUSDTE: Control<Date>;
    TERMSPAID: number;
    PRINCIPALOUTSTANDINGAMT: number;
    INTERESTRTE: number;
    OVERDUE30DAYS: number;
    OVERDUE60DAYS: number;
    OVERDUE90DAYS: number;
    OVERDUEABOVE90DAYS: number;
    OVERDUEABOVE120DAYS: number;
    LIVESTS: string;
    EXECUTIONDTE: Control<Date>;
    EXECUTIONOFFSET: number;
    SESSIONID: number;
    SESSIONCDE: string;
    CHECKED: boolean;
    EXPAPPLICANTROLEDSC: string;
    OVERDUERNTL: number;
    CUSTOMERNBR: string;
    PAIDRNTLTRMS: number;
    REMNRNTLTRMS: number;
    // following properties are from helper class
    STATUSDSC: string;
    CONTRACTNBR: string;
    EXPPROPOSALNBR: string;
    ASSETMAKEDSC: string;
    ASSETBRANDDSC: string;
    ASSETMODELDSC: string;
    RELEVANCE: number;
    CHRTPRTYCDE: string;
    IDTYPECDE: string;
    RENTALAMT: number;
    BRANCHNME: string;
    DATEOFBIRTH: Control<Date>;
    REGISTRATIONDTE: Control<Date>;
    IDEXPIRYDATE: Control<Date>;
    assetdsc: string;
    finanlcialProdname: string;
    enginenbr: string;
    chassisnbr: string;
    IDISSUEDATE: Control<Date>;
    ASSETUSAGECODE: string;
    IDTYPEDSC:string;
}