import { IBaseEntity } from "@NFS_Entity/Base-Entity/BaseEntity.model";
import { Control } from "src/Library";

export interface IPRPL_APLT_BANKInfo extends IBaseEntity {
    OTHERBRANCHIND: boolean;
    //above property exist in helper class
    APPLICANTID: number;
    BANKID: number;
    BANKNME: string;
    CONTACTNME: string;
    UNITNO: string;
    STREETNO: string;
    STREETNME: string;
    ADDRESS: string;
    COUNTRYID: number;
    CITYID: string;
    STATECDE: string;
    //CODE: any;
    ACCOUNTNME: string;
    BRANCHNME: string;
    ACCOUNTNBR: string;
    ACCOUNTTYPCDE: string;
    PHONENBR: string;
    STREETTYPCDE: string;
    FAX: string;
    EMAIL: string;
    EXECUTIONDTE: Control<Date>;
    EXECUTIONOFFSET: number;
    SESSIONID: number;
    SESSIONCDE: string;
    DISTRICTCDE: string;
    ADDRESSSTATUSCDE: string;
    ADDRESSTEMPLATECDE: string;
    ADDRESSTYPECDE: string;
    AMPHURID: number;
    BUILDINGNME: string;
    COMMENT: string;
    DISTRICT: number;
    FLOORDETAIL: string;
    MOO: string;
    POBOXADDRESS: string;
    POSTALCODE: string;
    PROPERTYNME: string;
    PROPERTYTYPECDE: string;
    PROVINCEID: number;
    ROOMNO: string;
    SOI: string;
    SUBDISTRICTCDE: number;
    TEMPLATEMAINID: string;
    TIMEINMONTH: number;
    TIMEINYEAR: number;
    TOWNCDE: number;
    TUMBONID: number;
    RESIDENCETYPECDE: string;
    HOMEVALUE: number;
    ATTENTIONTONME: string;
    LIVINGFROMDTE: Control<Date>;
    VERIFIEDIND: string;
    RESIDENCEOWNCOMMENTS: string;
    RESIDENCEOWNVALUE: number;
    BANKBPID: number;
    BANKBRANCHBPID: number;
    RESIDENCECDE: string;
    REGIONID: number;
    COUNTYID: number;
    OTOOTHRBRANCHNME: string;
    OTODEFAULTIND: boolean;
    ACCOUNTVERIFICATIONINDOTO: string;
    KOTAMADYAIDOTO: number;
    KECAMATANIDOTO: number;
    KELURAHANIDOTO: number;
    RWOTO: string;
    RTOTO: string;
    ADDRESSOTO: string;
    APPARTMENTNAMEOTO: string;
    NEWDATAIND: boolean;
    BPBANKSEQID: number;
    CURRENCYCDE: string;
    // following properties are to handle check box data types issues
    ACCOUNTVERIFICATIONINDOTO_Helper: boolean;
    INDEX: number;
    VLDMSGIND:number;
}