import { IBaseEntity } from "@NFS_Entity/Base-Entity/BaseEntity.model";
import { Control } from "src/Library";
import {IBP_CRDT_RTNG_CODEInfo, ISOCL_INTR_CODEInfo, IMEET_TYPE_CODEInfo, IPRPY_LOCN_CODEInfo, IBP_MAINInfo } from "./ProposalApplicantEntity.model.index";

export interface IPRPL_FILD_VIST_APMTInfo extends IBaseEntity {
    APPOINTMENTID: number;
    PROPOSALID: number;
    APPLICANTID: number;
    HOMEVISITIND: boolean;
    OFFICEVISITIND: boolean;
    FIREQIND: boolean;
    FIUSERID: number;
    FIPLANDTE: Control<Date>;
    FIREMINDDTE: Control<Date>;
    FIPLACE: string;
    FITIME: Control<Date>;
    COMMENTS: string;
    FICOMPLETIONDTE: Control<Date>;
    FISTARTTIME: Control<Date>;
    FIENDTIME: Control<Date>;
    FIHOMEVISITIND: boolean;
    FIOFFICEVISITIND: boolean;
    FICOMMENTS: string;
    FIRATINGCDE: string;   
    EXECUTIONDTE: Control<Date>;
    EXECUTIONOFFSET: number;
    SESSIONCDE: string;
    SESSIONID: number;
    FIELDAGENTID: number;
    FIELDAGENTIND: boolean;
    FLDVISITCMPLTD: boolean;
    ISSUBMITTED: boolean;
    ISSAVED: boolean;
    PARTYBEINGSURVEYED: string;
    DISTANCETOHOUSE: string; 
    ELECTRICITYVOLTAGE: number;
    HOUSELOCATIONCDE: string;
    OTHERVISITIND: boolean;
    OTHERVISIT: string;
    SURVEYMEETWITH: string;
    SURVEYPARTYNME: string;
    SURVEYSOCIALINTERACTIONCDE: string;
    SURVEYCONTACTNBR: string;
    ELECTRICITYSUBSCRIBERNBR: string;
    ELECTRICITYMONTHS: number;
    ELECTRICITYYEARS: number;    
    ELECTRICITYAMOUNT: number;
    PROPERTYTAXNBR: string;
    PROPERTYSIZEOFLAND: number;    
    PROPERTYSALEVALUE: string;
    OFFICELOCATIONCDE: string;
    ISFROMCAP: boolean;
    // following properties are from helper class
    USERID: number;
    USERNME: string;
    APPLICANTNAME: string;
    APPLICANTROLE: string;
    APPLICANTPHNE: string;
    APPLICANTEMAIL: string;
    REQUESTID: number;
    PARENTREQUESTID: number;
    FIELDAGENT: string;
    STATUSCODE: string;
    ProposalNumber: string;    
    MANUALIND: boolean;
    ISDISABLED: boolean;
    APPLICANTTYP: string;
    BPCRDTRTNGCODE: Array<IBP_CRDT_RTNG_CODEInfo>;
    SOCLINTRCODE: Array<ISOCL_INTR_CODEInfo>;
    MEETTYPECODE: Array<IMEET_TYPE_CODEInfo>;
    PRPYLOCNCODE: Array<IPRPY_LOCN_CODEInfo>;
    BPMAIN: Array<IBP_MAINInfo>;
    BPCOMPANYBRANCHID: number;
    
}