import { IBaseEntity } from "@NFS_Entity/Base-Entity/BaseEntity.model";
import { Control } from "src/Library";

export interface IPRPL_APLT_INDVInfo extends IBaseEntity {

    APPLICANTID: number;
    NATIONALITYCDE: string;
    //CODE: string;
    EMPLOYMENTTYPECDE: string;
    TITLECDE: string;
    MARITALSTATUSCDE: string;
    OCCUPATIONCDE: string;
    FIRSTNME: string;
    MIDDLENME: string;
    LASTNME: string;
    LICENSENUMBER: string;
    DATEOFBIRTH: Control<Date> | null;
    LICENSEEXPIRYDTE: Control<Date>;
    NUMBEROFDEPENDENTS: number;
    AGEINYEAR: number;
    AGEINMONTH: number;
    PRIVACYACT: string;
    SELFEMPLOYMENT: string;
    TIMEASCUSTOMER: string;
    GENDER: string;
    OTORLGNCDE: string;
    EMAILADDRESS: string;
    CUSTOMERNUMBER: string;
    SALUTATION: string;
    APPLICANTSTATUS: string;
    CHILDRENFLAG: string;
    IDCARDTYP: string;
    IDCARDNBR: string;
    IDCARDISSUEDTE: Control<Date>;
    IDCARDEXPIRYDTE: Control<Date>;
    BLACKLISTIND: boolean;
    FIRSTNMELOCAL: string;
    MIDDLENMELOCAL: string;
    LASTNMELOCAL: string;
    GUARANTORRELATIONSHIPCDE: string;
    EDUCATIONCDE: string;
    TITLECDELOCAL: string;
    EXECUTIONDTE: Control<Date>;
    SALARY: number;
    CREDITLIMIT: number;
    EDUCATIONLOCATIONCDE: string;
    EXECUTIONOFFSET: number;
    SESSIONID: number;
    SESSIONCDE: string;
    RACECDE: string;
    CONSENTTOSHARE: boolean;
    CREDITRATING: string;
    SELFEMPLOYED: string;
    CUSTOMERCDE: string;
    DBTRCTGYCODEOTO: string;
    OTOMOTHERMDNNME: string;
    OTOPLACEOFBIRTH: string;
    OTOAGMTCDE: string;
    VIPIND: boolean;
    CNTRYDOMCDE: string;
    TITLESUFFIX: string;
    CITIZENSHIPCDE: string;
    FAMILYCARDNO: string;
    NOOFDEPENDENTS: string;
    CUSTOMERCDEOL: string | null;
    // following properties are from helper class
    CURRENCYSYMBOL: string;
    APPLICANTROLE: string;
    DOB: string;
    APLICANTNAMEENABLE: boolean;
    ISFAMILYEXPOSURE: boolean;
    MONTHONBOOK: number;
    TIMEONBOOK: number;
    COUNTRYDSC: string;
    ISOTOEMPLOYEEIND: boolean;
    CALCULATECOMMISSIONIND: boolean;
    INVCOPTNCDE: string;
    ACCTYPCDE: string;
    KTPIND: boolean;
}